development:
  clients:
    default:
      uri: mongodb+srv://CaioMassucato:webcrawlerpaa@cluster0.sas1m.mongodb.net/Webcrawler?retryWrites=true&w=majority
      collection: questions

production:
  clients:
    default:
      uri: mongodb+srv://CaioMassucato:webcrawlerpaa@cluster0.sas1m.mongodb.net/Webcrawler?retryWrites=true&w=majority
      collection: questions